name: Conformance

on: [push, pull_request]

jobs:
  run-conformance:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.x'

    - name: Run HTTP conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.1.0
      with:
        functionType: 'http'
        validateMapping: false
        source: 'test/conformance'
        target: 'writeHTTP'
        runtime: 'nodejs10'
        tag: 'nodejs10_20200805_20_RC00'

    - name: Run event conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.1.0
      with:
        functionType: 'legacyevent'
        validateMapping: false
        source: 'test/conformance'
        target: 'writeLegacyEvent'
        runtime: 'nodejs10'
        tag: 'nodejs10_20200805_20_RC00'

    - name: Run cloudevent conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.1.0
      with:
        functionType: 'cloudevent'
        validateMapping: false
        source: 'test/conformance'
        target: 'writeCloudEvent'
        runtime: 'nodejs10'
        tag: 'nodejs10_20200805_20_RC00'